"""96-well plate row/column constants and shared well palette.

Extracted from ``well_viewer.runtime_app`` so that controllers and views can
reach plate geometry without importing the GUI monolith.
"""

from __future__ import annotations

from ui.theme import (
    WELL_COLOR_1,  WELL_COLOR_2,  WELL_COLOR_3,  WELL_COLOR_4,
    WELL_COLOR_5,  WELL_COLOR_6,  WELL_COLOR_7,  WELL_COLOR_8,
    WELL_COLOR_9,  WELL_COLOR_10, WELL_COLOR_11, WELL_COLOR_12,
    WELL_COLOR_13, WELL_COLOR_14, WELL_COLOR_15, WELL_COLOR_16,
    WELL_COLOR_17, WELL_COLOR_18, WELL_COLOR_19, WELL_COLOR_20,
    WELL_COLOR_21, WELL_COLOR_22, WELL_COLOR_23, WELL_COLOR_24,
    WELL_COLOR_25, WELL_COLOR_26, WELL_COLOR_27, WELL_COLOR_28,
    WELL_COLOR_29, WELL_COLOR_30, WELL_COLOR_31, WELL_COLOR_32,
    WELL_COLOR_33, WELL_COLOR_34, WELL_COLOR_35, WELL_COLOR_36,
    WELL_COLOR_37, WELL_COLOR_38, WELL_COLOR_39, WELL_COLOR_40,
    WELL_COLOR_41, WELL_COLOR_42, WELL_COLOR_43, WELL_COLOR_44,
    WELL_COLOR_45, WELL_COLOR_46, WELL_COLOR_47, WELL_COLOR_48,
)


PLATE_ROWS = list("ABCDEFGH")
PLATE_COLS = [f"{c:02d}" for c in range(1, 13)]  # "01" … "12"

WELL_COLORS = [
    WELL_COLOR_1,  WELL_COLOR_2,  WELL_COLOR_3,  WELL_COLOR_4,
    WELL_COLOR_5,  WELL_COLOR_6,  WELL_COLOR_7,  WELL_COLOR_8,
    WELL_COLOR_9,  WELL_COLOR_10, WELL_COLOR_11, WELL_COLOR_12,
    WELL_COLOR_13, WELL_COLOR_14, WELL_COLOR_15, WELL_COLOR_16,
    WELL_COLOR_17, WELL_COLOR_18, WELL_COLOR_19, WELL_COLOR_20,
    WELL_COLOR_21, WELL_COLOR_22, WELL_COLOR_23, WELL_COLOR_24,
    WELL_COLOR_25, WELL_COLOR_26, WELL_COLOR_27, WELL_COLOR_28,
    WELL_COLOR_29, WELL_COLOR_30, WELL_COLOR_31, WELL_COLOR_32,
    WELL_COLOR_33, WELL_COLOR_34, WELL_COLOR_35, WELL_COLOR_36,
    WELL_COLOR_37, WELL_COLOR_38, WELL_COLOR_39, WELL_COLOR_40,
    WELL_COLOR_41, WELL_COLOR_42, WELL_COLOR_43, WELL_COLOR_44,
    WELL_COLOR_45, WELL_COLOR_46, WELL_COLOR_47, WELL_COLOR_48,
]
